<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\OwnerRecord;

class OwnerRecordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $records = [
            [
                'property_name' => 'Signature Palm Villa Frond N',
                'area' => 'Palm Jumeirah',
                'property_number' => 'Villa N-24',
                'building_name' => 'Palm Frond N',
                'bedrooms' => '5 Bedrooms',
                'property_type' => 'Villa',
                'owner_name' => 'Sheikh Mansoor Al-Qasimi',
                'phone_number' => '+971 4 399 1122',
                'mobile_number' => '+971 50 882 1944',
                'email' => 'mansoor.qasimi@holding.ae',
                'notes' => 'High net-worth VIP owner. Looking for off-market cash buyer.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Burj Crown Luxury High Floor',
                'area' => 'Downtown Dubai',
                'property_number' => 'Unit 3804',
                'building_name' => 'Burj Crown',
                'bedrooms' => '2 Bedrooms',
                'property_type' => 'Apartment',
                'owner_name' => 'Alexander Romanov',
                'phone_number' => '+971 4 429 8810',
                'mobile_number' => '+971 52 441 9023',
                'email' => 'a.romanov@investgroup.ch',
                'notes' => 'Full Burj Khalifa and Fountain view. Currently tenanted until Nov 2026.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Marina Gate Waterfront Duplex',
                'area' => 'Dubai Marina',
                'property_number' => 'Duplex 1201',
                'building_name' => 'Marina Gate 2',
                'bedrooms' => '3 Bedrooms',
                'property_type' => 'Duplex',
                'owner_name' => 'Fatima Al-Zahra',
                'phone_number' => '+971 4 368 4400',
                'mobile_number' => '+971 55 901 3344',
                'email' => 'fatima.alzahra@emiratescapital.ae',
                'notes' => 'Upgraded marble flooring, private jacuzzi on terrace.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Dubai Hills Club Villas Facing Golf',
                'area' => 'Dubai Hills Estate',
                'property_number' => 'Villa CV-18',
                'building_name' => 'Club Villas',
                'bedrooms' => '4 Bedrooms',
                'property_type' => 'Villa',
                'owner_name' => 'Rajesh Mehta',
                'phone_number' => '+971 4 221 6677',
                'mobile_number' => '+971 50 334 1120',
                'email' => 'rajesh.mehta@omnitech.in',
                'notes' => 'Direct golf course view. Clean title deed ready for transfer.',
                'status' => 'active',
            ],
            [
                'property_name' => 'The Opus by Zaha Hadid Penthouse',
                'area' => 'Business Bay',
                'property_number' => 'Penthouse 1901',
                'building_name' => 'The Opus',
                'bedrooms' => '4 Bedrooms',
                'property_type' => 'Penthouse',
                'owner_name' => 'Jean-Pierre Laurent',
                'phone_number' => '+971 4 551 2299',
                'mobile_number' => '+971 58 776 5410',
                'email' => 'jp.laurent@luxuryestates.fr',
                'notes' => 'Furnished by Zaha Hadid Design. Hotel serviced amenities.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Arabian Ranches 3 Townhouse',
                'area' => 'Arabian Ranches',
                'property_number' => 'TH-08',
                'building_name' => 'Sun Cluster',
                'bedrooms' => '3 Bedrooms',
                'property_type' => 'Townhouse',
                'owner_name' => 'Elena Petrova',
                'phone_number' => '+971 4 430 7711',
                'mobile_number' => '+971 56 123 9880',
                'email' => 'elena.petrova@aurora.ae',
                'notes' => 'Corner plot with expanded landscaped garden. Single row.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Address Sky View Sky Collection',
                'area' => 'Downtown Dubai',
                'property_number' => 'Tower 1 - 4502',
                'building_name' => 'Address Sky View',
                'bedrooms' => '3 Bedrooms',
                'property_type' => 'Apartment',
                'owner_name' => 'Tariq Al-Hashemi',
                'phone_number' => '+971 4 362 9000',
                'mobile_number' => '+971 50 994 3211',
                'email' => 'tariq.hashemi@gulfholding.com',
                'notes' => 'Infinity sky bridge access. Serviced apartment with 8% guaranteed ROI.',
                'status' => 'active',
            ],
            [
                'property_name' => 'One at Palm Jumeirah Ultra Luxury',
                'area' => 'Palm Jumeirah',
                'property_number' => 'Residence 601',
                'building_name' => 'One at Palm Jumeirah (Omniyat)',
                'bedrooms' => '4 Bedrooms',
                'property_type' => 'Penthouse',
                'owner_name' => 'Maximilian Schmidt',
                'phone_number' => '+971 4 511 8822',
                'mobile_number' => '+971 54 321 0099',
                'email' => 'm.schmidt@bavaria-capital.de',
                'notes' => 'Managed by Dorchester Collection. Private beach & jetty berth included.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Cayan Tower Twisting Marvel',
                'area' => 'Dubai Marina',
                'property_number' => 'Unit 5208',
                'building_name' => 'Cayan Tower',
                'bedrooms' => '2 Bedrooms',
                'property_type' => 'Apartment',
                'owner_name' => 'Kareem Mostafa',
                'phone_number' => '+971 4 456 1234',
                'mobile_number' => '+971 55 678 1230',
                'email' => 'kareem.mostafa@niletech.eg',
                'notes' => 'High floor marina panoramic sunset view. Chiller free.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Emirates Hills Sector E Palace',
                'area' => 'Emirates Hills',
                'property_number' => 'Villa E-12',
                'building_name' => 'Sector E Master Villas',
                'bedrooms' => '6+ Bedrooms',
                'property_type' => 'Villa',
                'owner_name' => 'Sultan Hamdan',
                'phone_number' => '+971 4 360 0011',
                'mobile_number' => '+971 50 111 4455',
                'email' => 'sultan.hamdan@alhamdan.ae',
                'notes' => 'Custom built mansion, private cinema, underground 8-car garage.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Creek Horizon Tower Island View',
                'area' => 'Dubai Creek Harbour',
                'property_number' => 'Unit 1802',
                'building_name' => 'Creek Horizon Tower 1',
                'bedrooms' => '2 Bedrooms',
                'property_type' => 'Apartment',
                'owner_name' => 'Amina Al-Nuaimi',
                'phone_number' => '+971 4 233 4455',
                'mobile_number' => '+971 52 876 5432',
                'email' => 'amina.nuaimi@rasalkhaimah.gov.ae',
                'notes' => 'Frontline Central Park and Dubai Creek Tower view.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Sidra 2 Family Villa',
                'area' => 'Dubai Hills Estate',
                'property_number' => 'Villa S2-140',
                'building_name' => 'Sidra 2',
                'bedrooms' => '4 Bedrooms',
                'property_type' => 'Villa',
                'owner_name' => 'David O’Connor',
                'phone_number' => '+971 4 388 9012',
                'mobile_number' => '+971 56 789 0123',
                'email' => 'david.oconnor@dubailaw.ie',
                'notes' => 'Very close to King’s College Hospital & Dubai Hills Mall.',
                'status' => 'active',
            ],
            [
                'property_name' => 'IL Primo Opera District Full Floor',
                'area' => 'Downtown Dubai',
                'property_number' => 'Unit 6201',
                'building_name' => 'IL Primo',
                'bedrooms' => '5 Bedrooms',
                'property_type' => 'Penthouse',
                'owner_name' => 'Chen Wei',
                'phone_number' => '+971 4 445 6789',
                'mobile_number' => '+971 58 901 2345',
                'email' => 'chen.wei@shanghai-holdings.cn',
                'notes' => '5,000+ sqft ultra-luxurious full-floor overlooking Dubai Opera.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Executive Towers Prime Studio Suite',
                'area' => 'Business Bay',
                'property_number' => 'Studio 904',
                'building_name' => 'Executive Tower B',
                'bedrooms' => 'Studio',
                'property_type' => 'Apartment',
                'owner_name' => 'Sarah Jenkins',
                'phone_number' => '+971 4 369 8899',
                'mobile_number' => '+971 55 123 4567',
                'email' => 'sarah.jenkins@mediaone.uk',
                'notes' => 'Excellent rental history, currently rented on monthly contracts via Airbnb.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Whispering Pines Spanish Hacienda',
                'area' => 'Jumeirah Golf Estates',
                'property_number' => 'Villa WP-33',
                'building_name' => 'Whispering Pines',
                'bedrooms' => '4 Bedrooms',
                'property_type' => 'Villa',
                'owner_name' => 'Carlos Mendoza',
                'phone_number' => '+971 4 883 4500',
                'mobile_number' => '+971 50 654 3210',
                'email' => 'carlos.mendoza@ibero-trading.es',
                'notes' => 'Overlooking the 14th hole of Earth Course. Private pool & pergola.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Bluewaters Residences Sea Facing',
                'area' => 'Bluewaters Island',
                'property_number' => 'Building 3 - Unit 702',
                'building_name' => 'Bluewaters Residences 3',
                'bedrooms' => '3 Bedrooms',
                'property_type' => 'Apartment',
                'owner_name' => 'Zubair Khan',
                'phone_number' => '+971 4 399 8765',
                'mobile_number' => '+971 52 345 6789',
                'email' => 'zubair.khan@karachi-textiles.pk',
                'notes' => 'Unobstructed Ain Dubai & Arabian Gulf sea view.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Bayz by Danube Commercial Office',
                'area' => 'Business Bay',
                'property_number' => 'Office 1403',
                'building_name' => 'Bayz Tower',
                'bedrooms' => 'Commercial',
                'property_type' => 'Commercial',
                'owner_name' => 'Vikram Singhania',
                'phone_number' => '+971 4 558 7744',
                'mobile_number' => '+971 54 890 1234',
                'email' => 'vikram@singhaniagroup.com',
                'notes' => 'Fully fitted commercial grade office with 4 partitioned cabins.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Sobha Hartland Waterfront Villa',
                'area' => 'Mohammed Bin Rashid City',
                'property_number' => 'Villa SH-05',
                'building_name' => 'Hartland Forest Villas',
                'bedrooms' => '5 Bedrooms',
                'property_type' => 'Villa',
                'owner_name' => 'Nasser Al-Subaie',
                'phone_number' => '+971 4 420 5566',
                'mobile_number' => '+971 50 789 4561',
                'email' => 'nasser.subaie@riyadh-invest.sa',
                'notes' => 'Forest facing villa. Private elevator, double-height ceiling living room.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Emaar Beachfront Sunrise Bay',
                'area' => 'Dubai Harbour',
                'property_number' => 'Unit 1506',
                'building_name' => 'Sunrise Bay Tower 1',
                'bedrooms' => '2 Bedrooms',
                'property_type' => 'Apartment',
                'owner_name' => 'Olga Ivanova',
                'phone_number' => '+971 4 366 1199',
                'mobile_number' => '+971 56 456 7890',
                'email' => 'olga.ivanova@nordic-travel.se',
                'notes' => 'Direct private beach access. High holiday home income track record.',
                'status' => 'active',
            ],
            [
                'property_name' => 'Tilal Al Ghaf Harmony Villa',
                'area' => 'Tilal Al Ghaf',
                'property_number' => 'Villa H1-22',
                'building_name' => 'Harmony 1',
                'bedrooms' => '4 Bedrooms',
                'property_type' => 'Villa',
                'owner_name' => 'Faisal Al-Mutawa',
                'phone_number' => '+971 4 458 9900',
                'mobile_number' => '+971 55 890 2345',
                'email' => 'faisal.mutawa@kuwait-oil.kw',
                'notes' => 'Garden suite upgrade included. Walking distance to Crystal Lagoon.',
                'status' => 'active',
            ],
        ];

        foreach ($records as $data) {
            OwnerRecord::firstOrCreate(
                ['property_number' => $data['property_number'], 'building_name' => $data['building_name']],
                $data
            );
        }
    }
}
